api_key_file: config/api_keys/la.yaml
data_dir: data/la
gtfs_filename: data/la/la_gtfs.zip
gtfs_url: https://gitlab.com/LACMTA/gtfs_bus/raw/master/gtfs_bus.zip
name: la
realtime_url: https://api.goswift.ly/real-time/lametro/gtfs-rt-trip-updates
requires_key: true
sqlite_db: data/la/la.db
timezone: '-8'
cache_filename: data/la/la.csv
graph_filename: data/la/la_graph.json
shp_folder: data/la/shp
