api_key_file: config/api_keys/sanfrancisco.yaml
data_dir: data/sanfrancisco
gtfs_filename: data/sanfrancisco/sanfrancisco_gtfs.zip
gtfs_url: http://api.511.org/transit/datafeeds?operator_id=SF
name: sanfrancisco
realtime_url: https://api.511.org/transit/tripupdates?agency=SF
requires_key: true
sqlite_db: data/sanfrancisco/sanfrancisco.db
timezone: '-8'
cache_filename: data/sanfrancisco/sanfrancisco.csv
graph_filename: data/sanfrancisco/sanfrancisco_graph.json
shp_folder: data/sanfrancisco/shp
